branches:
  only:
  - master
language: python
python:
- '2.7'
before_install:
- git config --global user.name "Travis CI"
- git config --global user.email "tay@taybird.com"
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
install:
- pip install -r requirements.txt
script:
- ./build
deploy:
  provider: s3
  local_dir: static
  bucket: taybird-aboutme
  skip_cleanup: true
  acl: public_read
  region: us-west-2
  secret_access_key:
    secure: GGi1jEExfyKkSUolqQsEvl4fr2gZzLVw23a5XIn+ymivUYDWHdTXGr6tz/GV/V9uqBB5KUucYmaFEU+MyZX6zDuWaJtp2S2mDxRrhMGhAXjSbSwok7ZMbfUYebCKv741Yk6eOOO8Y6RtvA/ao1mTApB5JrybyDaRTqv5DYpQDprkY1G2mXLMMpTh91PXS4w4eJIqkh+BI78Nuy1tgRcKvenj7HxHyucZb9gBSI+WpZYfCO5jl5+tTcRIikTwqsKMLl1XLm8fq2r0grPBUHYMG7XRvzzOzv306W+fCxxBM+3dyhwC8V56Bi3anBTa1D85QS1kVSxDajLmht4D8ry1QmjtfP+HPuuhOsanPuzlsxl7U56X2QvTJTlmUbZecb4P6w1ejpDR8JT9MkomPffVTPSyM7E8X0A0YN0AI5dacDqTeU21+1U86A6vhN+aQSKWMaY8CT4+ivHl8NSdb1bbhG63JJYGj+UJCEhXXQzb4th2NRN2iZoqWBr8VSDTYf2sbteFE26GYeIup4/amnxvKo2Y2jq0Mx/404LpScB0bVlVz5mOKcQFm7dSe1ZAaGkrwueE9gDTbA/PGcDq6vx6809DnnG1WJL+X9P9c+EkXb/CUMBZ+URKpsogp/H4Fq3W0Kcrra+C+k+xtzn+WDK+nVGTHC8rlVBLKhbHEKp9UrI=
  access_key_id:
    secure: Y+lHUUa9Z6E2GMrjQHbqRzCJ7g5De/XLryDHV3tQ+vhqufP5zMGFcLc9Bx3gKfz8JSQKTUKfedxEa3B92tcguXPoCubsSQVoA6DQ09dakH5CSez0+b5WTtU5C1l4THFKLdTv57YbuNl+XFNekSdjJkxpZ+bsi9WUouQw1Ce+WcWMnuckkvCq9rBofGAe5VFMV9xMgbcN+kkRW4EEEa4cbRpQY7pw/G2VuO4mR2xpry6b4du2uxvhDHQlj4R2dQLe9BsbGlfaHJNvbaY7FIy3Gmn8yYi8XhKllZuBs1ayvhfSyjNDbXovai51D45S/BvZPniEXxsJEqhnmJcJRID6/CwbVLXiEcq3+QIwnyPkY5B7/4yeu2avVBFTMZE6ann98sdB6FdTINnSw7WDrfFIiQ8vvec51HiKz3BtM1MeO+wsLSYlpkJkqNso8XMGjeqlv2P0d103XxGfuxwmeyQSb1siiaevB9kCgq1To07gSGYWKg65LHNJsxsDlIrSlzSFqOK9zjcYKzjtxFXYCNesLa+SFQQE+m+ttN8ub9kL69JivRJfE9I5p+B7Hiw0hRf6FaX3pzy8UYI+i0kRkqjzrfSmPDUJh+aYQE70bm97OtBDXVLEBA4WkatLIXOZqt10pwtg6hNCJGgZMKLapViD9S+gMP+dn0ctuaRV1xgy/pg=
