branches:
  only:
  - master
language: python
python:
- '2.7'
before_install:
- git config --global user.name "Travis CI"
- git config --global user.email "tay@taybird.com"
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
install:
- pip install -r requirements.txt
script:
- ./build
deploy:
  provider: s3
  region: us-west-2
  local_dir: static
  bucket: taybird-aboutme
  detect_encoding: true
  acl: public_read
  secret_access_key:
    secure: hrJ9kFYokaoWbYdHyzFMnZTfTmNHldokzepojE7oEXGwlp9GugbQOdg01/GuE8bvANIwqibxwjjf7FpJtb+sHeNSC7QFHYOMY31MGuiLGw8kuEt9a4A9GYLZZhDPjQFiNMmr2wY5WntuhSXm57DIBhjIWNG2I1pW7yoUPw2zvqdERyk0HjZecNJh8Vtn8688aQbem5bMgvNoZpp0CB4fMxcjLpf7UqaAdiQ1yQ/vumWHwrVL7dXoLLA/vQNcbWo9W9LEisnYoQPznHWfTq6BdA4FTZtVLVxvifyC4kBspKialLmBHYJpj/I2Z4eAj8cNgM2CWsoqw6gJcKdefBEWbKVdbAL8h3QiLKdA240ZLtBN80iYUYQ2Rj5KrSdgGCi4McPux2s0vr372FUUNds+Swha/GVwdloGptV1zRRnHOxPDI76x4YkhTuf72YgQ7vDwxGeQ13xgH7i30mIlByzXjDM16DKPG9vDHY9YxGUpmHcF3IXWewcm6K8AIRoha2PG7bS0f+B0bM4GeBt7Cpr/Djwp8tk4qUqBWbrhVFeG0I16uvTm8hu/TiKOZq+73i84GHey4ZcJIouebBjEIdkZRO/qMTFjpmaGSK2k3fnB5wCvZXZCCHVV4lh+4XbJmnuscqaURkkyzysoEZ+pEK4ymwAO6YUkcGVTsrm5MpAZ8Y=
  access_key_id:
    secure: kngu8r1K44IAUYBmqT0CYlguU1/wDqXMcBoz16hYf7NYFQ9eNO1gtl7inVXwLwsiONupA3Qis7YJ+JIzkgLqLtW150mG4whM3RI890qb7WwqLsrfCW8z72/xJJMGVR+KX+MEpGgBVfi+Rjo2PjT5ORXKrsrbUEgywkK/Nm60T8X0wq8JRPk40+W1vDQke5QM56tsMeOwtLiulXqaO/+SFD6UYftfk7Hi05s5e8eKKCVg3FYibh72FOXkWF2rGypkMPjP9u/LgjP8hFLih5YyQMDb4tMKmRkXGuxHzPthpVuFoOdEJ40xH7a7DS+NexDtZxVOOSVqo7I0E9sTp7O3kvc++Z8oRIZMSORdj63kg64wI6kP4A5faHRwVvEdS1IbFwP8QDAzzut1irW6cJREutRs4hnvhjeibPDEbrmmUHQ6DL9dBbsntNEY85VKZC1IzhwlUh2DZnHGnRkLrSvkgMTKg8mTIZE5SJCuwlvpyOQ9kA8OZzWSSAudxt5R+5LgTOaWfPH4PQsrXIGISSTYLKXH+QRYkGWQcQ6glZrqjEEgXAydWtUn9TtCPW9acB4+wUD66FhYbvWpqDq9LsVnGE6PMrkg/JcIKBN40uBq7Qk2eR/5Qebpl5HXaXAwEC2bO7nY+HZ+QTr70zZUClbP0WvGRJatkAUXplq2WvguEiE=
  skip_cleanup: true
